version: '3'

services:
  habits:
    image: "awmuncy/habits:${tag}"
    ports: 
      - "5000"
    labels: 
      - "traefik.http.middlewares.habits-secure-${branch}.basicauth.users=awmuncy:{SHA}A8EvQY6ms//hw/+MgNHCOOAmlBQ="
      - traefik.http.routers.habits-${branch}.middlewares=habits-secure-${branch}
      - traefik.http.middlewares.habit-non-secure-to-habit-secure-${branch}.redirectscheme.scheme=https
      - traefik.http.routers.habit-non-secure-${branch}.middlewares=habit-non-secure-to-habit-secure-${branch}
      - traefik.http.routers.habit-non-secure-${branch}.rule=Host(`${branch}.dev.checkyourhabit.com`)
      - traefik.http.routers.habit-non-secure-${branch}.entrypoints=web
      - traefik.http.routers.habits-${branch}.rule=Host(`${branch}.dev.checkyourhabit.com`)  
      - traefik.http.services.habits-${branch}.loadbalancer.server.port=5000
      - traefik.http.routers.habits-${branch}.tls=true
      - traefik.http.routers.habits-${branch}.tls.certresolver=myresolver
    networks:
      default:   
    

networks:
  default:
    external:
      name: gateway