version: '3'

services:
  habits:
    image: "awmuncy/habits"
    ports:
      - "5000"
    labels:
      - "traefik.http.middlewares.habits-secure.basicauth.users=awmuncy:{SHA}A8EvQY6ms//hw/+MgNHCOOAmlBQ="
      - traefik.http.routers.habits.middlewares=habits-secure
      - traefik.http.middlewares.habit-non-secure-to-habit-secure.redirectscheme.scheme=https
      - traefik.http.routers.habit-non-secure.middlewares=habit-non-secure-to-habit-secure
      - traefik.http.routers.habit-non-secure.rule=Host(`${branch}.dev.checkyourhabit.com`)
      - traefik.http.routers.habit-non-secure.entrypoints=web
      - traefik.http.routers.habits.rule=Host(`${branch}.dev.checkyourhabit.com`)
      - traefik.http.services.habits.loadbalancer.server.port=5000
      - traefik.http.routers.habits.tls=true