{{ $site_domain := ( print (ternary (print .Values.siteSubdomainPrefix "." .Values.Env ".") "" (ne .Values.Env "prod")) .Values.domain ) }}
{{ $app_domain := ( print (ternary (print .Values.appSubdomainPrefix "." .Values.Env ".") "" (ne .Values.Env "prod")) .Values.domain ) }}
{{ $ident := (print .Release.Name "-" .Release.Revision "-" .Values.Env) }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: habits-site-ingress-{{ $ident }}
  namespace: habits-{{ .Values.Env }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls: 
  - hosts:
    - {{ $app_domain }}
    secretName: ssl-for--{{ $site_domain }}
  rules:
  - host: {{ $site_domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: habits-service-{{ $ident }}
            port: 
              number: 5173
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: habits-app-ingress-{{ $ident }} 
  namespace: habits-{{ .Values.Env }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls: 
  - hosts:
    - {{ $app_domain }}
    secretName: ssl-for--{{ $app_domain }}
  rules:
  - host: {{ $app_domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: habits-service-{{ $ident }} 
            port: 
              number: 5499